spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: mediumdb
      auto-index-creation: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: suvadip.webshark@gmail.com
    password: ${MAIL_PASSWORD}
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}

server:
  port: 8080